version: '3'
services:
  db:
    image: postgres:11-alpine
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "9000:8080"
